#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <dirent.h>
#include <sys/stat.h>
#include <sys/wait.h>
#include <unistd.h>

#define MAX_TESTS 256
#define MAX_PATH  512

static int ends_with(const char *s, const char *suffix) {
    size_t slen = strlen(s), suflen = strlen(suffix);
    if (slen < suflen) return 0;
    return strcmp(s + slen - suflen, suffix) == 0;
}

static int starts_with(const char *s, const char *prefix) {
    return strncmp(s, prefix, strlen(prefix)) == 0;
}

/* Extract test name from filename: "test_foo.c" -> "foo" */
static void test_name_from_file(const char *filename, char *out, size_t out_sz) {
    /* skip "test_" prefix */
    const char *start = filename + 5;
    size_t len = strlen(start) - 2; /* remove ".c" */
    if (len >= out_sz) len = out_sz - 1;
    memcpy(out, start, len);
    out[len] = '\0';
}

/* Glob test_*.c files in a concept directory */
static int glob_tests(const char *concept, char tests[][MAX_PATH], int max) {
    char dir[MAX_PATH];
    snprintf(dir, sizeof(dir), "%s", concept);

    DIR *d = opendir(dir);
    if (!d) {
        fprintf(stderr, "Cannot open directory: %s\n", dir);
        return -1;
    }

    int count = 0;
    struct dirent *ent;
    while ((ent = readdir(d)) != NULL && count < max) {
        if (starts_with(ent->d_name, "test_") && ends_with(ent->d_name, ".c")) {
            /* skip test_main.c (generated) */
            if (strcmp(ent->d_name, "test_main.c") == 0) continue;
            strncpy(tests[count], ent->d_name, MAX_PATH - 1);
            tests[count][MAX_PATH - 1] = '\0';
            count++;
        }
    }
    closedir(d);

    /* Sort for deterministic order */
    for (int i = 0; i < count - 1; i++) {
        for (int j = i + 1; j < count; j++) {
            if (strcmp(tests[i], tests[j]) > 0) {
                char tmp[MAX_PATH];
                memcpy(tmp, tests[i], MAX_PATH);
                memcpy(tests[i], tests[j], MAX_PATH);
                memcpy(tests[j], tmp, MAX_PATH);
            }
        }
    }

    return count;
}

/* Generate test_main.c for a concept */
static int generate_test_main(const char *concept, char tests[][MAX_PATH], int count) {
    char path[MAX_PATH];
    snprintf(path, sizeof(path), "%s/test_main.c", concept);

    FILE *f = fopen(path, "w");
    if (!f) {
        fprintf(stderr, "Cannot create %s\n", path);
        return -1;
    }

    fprintf(f, "/* Generated by build — do not edit */\n");
    fprintf(f, "#include <stdio.h>\n");
    fprintf(f, "#include <stdlib.h>\n");
    fprintf(f, "#include <string.h>\n");
    fprintf(f, "#include <sys/wait.h>\n");
    fprintf(f, "#include <unistd.h>\n\n");

    /* Declare all test functions */
    for (int i = 0; i < count; i++) {
        char name[MAX_PATH];
        test_name_from_file(tests[i], name, sizeof(name));
        fprintf(f, "extern void test_%s(void);\n", name);
    }

    fprintf(f, "\ntypedef struct { const char *name; void (*fn)(void); int expect_abort; } Test;\n\n");
    fprintf(f, "int main(void) {\n");
    fprintf(f, "    Test all[] = {\n");

    for (int i = 0; i < count; i++) {
        char name[MAX_PATH];
        test_name_from_file(tests[i], name, sizeof(name));
        int expect_abort = ends_with(name, "_aborts");
        fprintf(f, "        { \"%s\", test_%s, %d },\n", name, name, expect_abort);
    }

    fprintf(f, "    };\n");
    fprintf(f, "    int n = sizeof(all) / sizeof(all[0]);\n");
    fprintf(f, "    int passed = 0, failed = 0;\n\n");
    fprintf(f, "    for (int i = 0; i < n; i++) {\n");
    fprintf(f, "        fflush(stdout);\n");
    fprintf(f, "        pid_t pid = fork();\n");
    fprintf(f, "        if (pid == 0) {\n");
    fprintf(f, "            all[i].fn();\n");
    fprintf(f, "            _exit(0);\n");
    fprintf(f, "        }\n");
    fprintf(f, "        int status;\n");
    fprintf(f, "        waitpid(pid, &status, 0);\n");
    fprintf(f, "        int clean_exit = WIFEXITED(status) && WEXITSTATUS(status) == 0;\n");
    fprintf(f, "        int pass = all[i].expect_abort ? !clean_exit : clean_exit;\n");
    fprintf(f, "        if (pass) {\n");
    fprintf(f, "            printf(\"  PASS  %%s\\n\", all[i].name);\n");
    fprintf(f, "            passed++;\n");
    fprintf(f, "        } else {\n");
    fprintf(f, "            printf(\"  FAIL  %%s\\n\", all[i].name);\n");
    fprintf(f, "            failed++;\n");
    fprintf(f, "        }\n");
    fprintf(f, "    }\n\n");
    fprintf(f, "    printf(\"\\n%%d passed, %%d failed, %%d total\\n\", passed, failed, n);\n");
    fprintf(f, "    return failed > 0 ? 1 : 0;\n");
    fprintf(f, "}\n");

    fclose(f);
    return 0;
}

/* Collect non-test .c files (the concept implementation) */
static int glob_sources(const char *concept, char sources[][MAX_PATH], int max) {
    DIR *d = opendir(concept);
    if (!d) return -1;

    int count = 0;
    struct dirent *ent;
    while ((ent = readdir(d)) != NULL && count < max) {
        if (ends_with(ent->d_name, ".c")
            && !starts_with(ent->d_name, "test_")) {
            snprintf(sources[count], MAX_PATH, "%s/%s", concept, ent->d_name);
            count++;
        }
    }
    closedir(d);
    return count;
}

static int cmd_test(const char *concept) {
    char tests[MAX_TESTS][MAX_PATH];
    int test_count = glob_tests(concept, tests, MAX_TESTS);
    if (test_count < 0) return 1;
    if (test_count == 0) {
        printf("No tests found in %s/\n", concept);
        return 0;
    }

    printf("Found %d tests in %s/\n\n", test_count, concept);

    /* Generate test_main.c */
    if (generate_test_main(concept, tests, test_count) != 0) return 1;

    /* Build compile command */
    char cmd[4096];
    int pos = snprintf(cmd, sizeof(cmd),
        "cc -std=c11 -Wall -Wextra -I%s -I. ", concept);

    /* Add source files */
    char sources[MAX_TESTS][MAX_PATH];
    int src_count = glob_sources(concept, sources, MAX_TESTS);
    for (int i = 0; i < src_count; i++) {
        pos += snprintf(cmd + pos, sizeof(cmd) - pos, "%s ", sources[i]);
    }

    /* Add test files */
    for (int i = 0; i < test_count; i++) {
        pos += snprintf(cmd + pos, sizeof(cmd) - pos, "%s/%s ", concept, tests[i]);
    }

    /* Add generated test_main.c and output */
    snprintf(cmd + pos, sizeof(cmd) - pos,
        "%s/test_main.c -o %s/test_%s -lm", concept, concept, concept);

    printf("Compiling...\n");
    fflush(stdout);
    int rc = system(cmd);
    if (rc != 0) {
        fprintf(stderr, "Compilation failed\n");
        return 1;
    }

    /* Run */
    char run[MAX_PATH];
    snprintf(run, sizeof(run), "%s/test_%s", concept, concept);
    printf("\n");
    fflush(stdout);
    return system(run);
}

static void usage(void) {
    fprintf(stderr, "Usage: ./build test <concept>\n");
}

int main(int argc, char **argv) {
    if (argc < 3) {
        usage();
        return 1;
    }

    if (strcmp(argv[1], "test") == 0) {
        return cmd_test(argv[2]) ? 1 : 0;
    }

    usage();
    return 1;
}
